# Logging levels for our application
logging:
  level:
    com.discounts.nearby: [ trace ]

# Common Spring settings
spring:
  application:
    name: discounts-nearby
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
  mail:
    host: smtp.yandex.ru
    username: ${mailUser}
    password: ${mailPassword}
    port: 465
    protocol: smtps
server:
  port: 3030

